name: 更新Changelog

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  update_changelog:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: 设置Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install github-changelog-generator
          
      - name: 生成Changelog
        run: |
          if [ ! -f CHANGELOG.md ]; then
            touch CHANGELOG.md
          fi
          
          echo "## 更新内容 (PR #${{ github.event.pull_request.number }})" > temp_changelog.md
          echo "- ${{ github.event.pull_request.title }}" >> temp_changelog.md
          
          if [ ! -z "${{ github.event.pull_request.body }}" ]; then
            echo "" >> temp_changelog.md
            echo "${{ github.event.pull_request.body }}" | sed 's/^/  /' >> temp_changelog.md
          fi
          
          echo "" >> temp_changelog.md
          cat CHANGELOG.md >> temp_changelog.md
          mv temp_changelog.md CHANGELOG.md
          
      - name: 提交Changelog变更
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add CHANGELOG.md
          git commit -m "自动更新Changelog: PR #${{ github.event.pull_request.number }}" || echo "没有变更需要提交"
          
      - name: 推送变更
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }} 